### ISSUE TITLE
Allow rule create call without setting field

### ISSUE THREAD

**Issue by Vovke** [paritytech/github-issue-sync#14]
Currently in order to create a rule we call `https://github-issue-sync.parity-prod.parity.io/api/v1/rule/repository/{org_name}/{repo_name}` while required to provide `project_field` and `project_field_value`. Setting those fields shouldn't be mandatory in order to create a rule. 
The only mandatory field should be `project_number`

**Comment by mutantcornholio** [comment]
Just to be clear: if we're adding an issue to the board without setting `project_field` and `project_field_value`, it'll add issue with "No status" status. 
That **is** the expected result, right?
![Screen Shot 2022-04-29 at 11 39 47](https://user-images.githubusercontent.com/588262/165921041-26814c60-c006-4266-9690-5826a927c87c.png)

**Comment by Vovke** [comment]
yes, thats expected behaviour

**Comment by joao-paulo-parity** [comment]
closed by #15

**Comment by joao-paulo-parity** [comment]
close by #17
