### ISSUE TITLE
Feature: sync labels across repositories 

### ISSUE THREAD

**Issue by mordamax** [paritytech/github-issue-sync#19]
**Problem**:
Known fact: projects may include issues from different repositories. When team is working with all issues in a project, it'd be nice if labels are "speak same language", e.g are consistent across repos. Otherwise it's hard to aggregate/group/sort and expect query to work consistently.

**Example 1**: team might use specific levels of prioritizations like "P1", "P2", "P3" (with some nice icons), while one repo has `P1 -🔥` the other one would be just `P1`. While meaning is the same - there's no way to filter all issues by P1 priority, as filters technically are different from repo to repo. 

**Example 2**: as a team, we're reviewing all tickets from the board, and adding according labels to all issues from different repo's which help then to group & sort issues efficiently - (like `effort: 🔥🔥`, `impact: 💎💎`, `¯\_(ツ)_/¯`, etc) => since labels are inconsistent - then the marking doesn't allow us to sort/group them efficiently too

In order to keep project with several repos consistent, we need to figure out the way to define "project level" labels, which may be optionally distributed across the repositories.
I'm not sure exact constraints yet, how this will operate with existing labels etc, but we can discuss

**Comment by joao-paulo-parity** [comment]
As mentioned on Matrix, I see two problems with implementing this here.

First, it would require adding more permissions (for example [accessing the Labels APIs](https://docs.github.com/en/rest/issues/labels#about-the-labels-api)) and handling more webhook events (for example [team_add](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#team_add)).

Second I think managing labels doesn't fit in what github-issue-sync is intended to do. I'm comfortable with having it as a tool focused on (issue <-> board) interactions and would prefer to put "project management"-esque features such as this one in another project.
