### ISSUE TITLE
Make sync rules' management easier to work with for operators

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/github-issue-sync#20]
# Problem

Currently all sync rules are managed through the API. We provide some `curl` examples for how to use the API but there are alternatives for further enhancing the operators' usability experience.

# Solution

To make the sync rules' management easier to work with for operators, we could

Alternative 1: Provide OpenAPI specification for the API. That way operators could use the specification in whatever REST client they want e.g. Postman, Insomnia, etc.

Alternative 2: Implement CRUD Rules UI.

**Comment by mordamax** [comment]
Alternative 2: you mean Swagger UI, or similar, not implementing it from scratch ?
it may allow to run these queries

**Comment by joao-paulo-parity** [comment]
> Alternative 2: you mean Swagger UI, or similar, not implementing it from scratch ? it may allow to run these queries

Alternative 2 would use some existing project to connect to the database, like https://github.com/priyank-purohit/PostGUI#introduction for example, or be a minimal table-based UI coded by us.

If it has anything to do with OpenAPI I prefer for us to only generate the specification and let operators use it in whatever REST client app they want (i.e. we'd not use Swagger UI).

**Comment by mutantcornholio** [comment]
> If it has anything to do with OpenAPI I prefer for us to only generate the specification and let operators use it in whatever REST client app they want (i.e. we'd not use Swagger UI).

I'm not too familiar with the operators, but are those a type of people that usually have a preferred OpenAPI client app?

**Comment by joao-paulo-parity** [comment]
> > If it has anything to do with OpenAPI I prefer for us to only generate the specification and let operators use it in whatever REST client app they want (i.e. we'd not use Swagger UI).
> 
> I'm not too familiar with the operators, but are those a type of people that usually have a preferred OpenAPI client app? I don't have one, and I don't think that I even used one before

The users I have in mind for "operators" are ones in management-esque positions who are interested in managing rules for tracking teams, but specifically GitHub teams so they very likely are tied to engineering. Being heads and/or leads of engineering implies they should be familiar with OpenAPI and REST clients. One example was Vova and he even showed us the client he used in one of the meetings.

I don't have a huge problem with Swagger UI but I feel like it won't be useful. Those who know about OpenAPI and REST Clients will just use their own client instead of Swagger UI, while those who don't know are more comfortably served by a UI table which is way more convenient and direct to use rather than have to deal with `N` manual JSON API calls.

As a starting point we can generate the specification and say "Here's a specification, feel free to import it to your preferred REST client (e.g. [Postman](https://www.postman.com/downloads))". After that I expect we might get no complaints (users are satisfied with their clients) or we might get a feedback along the lines of "I tried to use OpenAPI and didn't like it, it was too complicated and/or inconvenient". I find it very unlikely that we'll get the feedback of "I don't want to use a REST client **and** I don't want to use a UI table either" which is where Swagger UI would fit.

In any case we can simply generate the OpenAPI first and decide if we want to go with Swagger UI in a separate ticket. I think having the specification in the first place is more important.

**Comment by mutantcornholio** [comment]
What do you think about asking end users of the feature directly, prior to implementing any of the options?

**Comment by joao-paulo-parity** [comment]
> What do you think about asking end users of the feature directly, prior to implementing any of the options?

Alright

**Comment by mordamax** [comment]
We won't continue developing this project
