### ISSUE TITLE
Update GraphQL queries to Project V2

### ISSUE THREAD

**Issue by Bullrich** [paritytech/github-issue-sync#46]
`ProjectNext` query is deprecated and soon will stop working.

We need to update to use `ProjectV2`.

[Example call](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects#using-variables)

[Documentation](https://docs.github.com/en/graphql/reference/objects#projectv2)

**Comment by mordamax** [comment]
looks like could be closed
