### ISSUE TITLE
Not working on private repositories

### ISSUE THREAD

**Issue by Bullrich** [paritytech/github-issue-sync#56]
[addProjectV2ItemById](https://docs.github.com/en/graphql/reference/mutations#addprojectv2itembyid) is not working on private repositories.

I have been calling the following mutation:
```gql
mutation($project: ID!, $issue: ID!) {
  addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
    item {
      id
    }
  }
}
```

and it does work on public repositories with public issues, but when I call this same endpoint in a private repository I get the following error:
`GraphqlResponseError: Request failed due to following response errors:`.

---

I do not know if this problem comes from my side so I created a discussion in GitHub's organization.

[addProjectV2ItemById does not work in private repositories #46505](https://github.com/orgs/community/discussions/46505)

**Comment by mordamax** [comment]
@Bullrich sounds similar to me as if you'd be mentioning the issue of private repo in a public one, or transferring issue from private to public, github doesn't let you do this to prevent accidental leak out sensitive info/details in private repos

**Comment by Bullrich** [comment]
> @Bullrich sounds similar to me as if you'd be mentioning the issue of private repo in a public one, or transferring issue from private to public, github doesn't let you do this to prevent accidental leak out sensitive info/details in private repos

That could have been true with old projects but with the new project (beta) ™️ it *shouldn't* work like that, because we are able to add private issues to projects manually.

So it could be that this was disabled in the past for the reason you mention (if issue is private do not allow to move it into a public repo) but forgot that projects are no longer private/public repos.
